# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk15

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту sergioparovozov@gmail.com если сборка упала
notifications:
  email:
    recipients:
      - sergioparovozov@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
env:
  global:
  - CODECOV_TOKEN="1310777b-c09d-4cf7-8063-3eee43cfc7c4"
